# Generated by Django 4.1.3 on 2022-12-05 17:53

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
