# Generated by Django 4.1.3 on 2022-12-07 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uitshare_main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_uploader', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='course',
            name='by_user',
            field=models.ForeignKey(db_column='by_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_creations', to=settings.AUTH_USER_MODEL, verbose_name='By User'),
        ),
        migrations.AddField(
            model_name='course',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='uitshare_main.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='by_user',
            field=models.ForeignKey(db_column='by_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_creations', to=settings.AUTH_USER_MODEL, verbose_name='By User'),
        ),
    ]
